### ISSUE TITLE
composer.lock not present

### ISSUE THREAD

**Issue by arjank** [Potherca/flysystem-github#2]
The `composer.lock` file is not present in the project, probably because it's listed in the `.gitignore` file. I would expect this file to be present in the repository. What's the reason it is ignored?

**Comment by Potherca** [comment]
Mostly because this project is set up using The Php League Skelleton which dictates this desicion.
In short it boils down to "Commit the `.lock` for applications, not packages".

More info can be found at https://github.com/thephpleague/skeleton/pull/34
